// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A message with unsigned integer slice fields.
/// message UnsignedIntFields {
///    
///     // A `u8` slice field.
///     one: []u8 = 1;
///    
///     // A `u16` slice field.
///     two: []u16 = 2;
///    
///     // A `u32` slice field.
///     three: []u32 = 3;
///    
///     // A `u64` slice field.
///     four: []u64 = 4;
///    
///     // A `u128` slice field.
///     five: []u128 = 5;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct UnsignedIntFields {
    #[serde(skip_serializing_if = "Option::is_none")]
    one: Option<Vec<u8>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    two: Option<Vec<u16>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    three: Option<Vec<u32>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    four: Option<Vec<u64>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    five: Option<Vec<u128>>,
}

impl UnsignedIntFields {
    //! Field: `one`

    /// Gets the field: `one`.
    #[must_use]
    pub fn one(&self) -> Option<&Vec<u8>> {
        self.one.as_ref()
    }

    /// Sets the field: `one`. Returns the previous value.
    pub fn set_one<F>(&mut self, one: F) -> Option<Vec<u8>>
    where
        F: Into<Option<Vec<u8>>>,
    {
        let one: Option<Vec<u8>> = one.into();
        std::mem::replace(&mut self.one, one)
    }

    /// Sets the field: `one`. Returns the struct itself.
    #[must_use]
    pub fn with_one<F>(mut self, one: F) -> Self
    where
        F: Into<Option<Vec<u8>>>,
    {
        self.set_one(one);
        self
    }
}

impl UnsignedIntFields {
    //! Field: `two`

    /// Gets the field: `two`.
    #[must_use]
    pub fn two(&self) -> Option<&Vec<u16>> {
        self.two.as_ref()
    }

    /// Sets the field: `two`. Returns the previous value.
    pub fn set_two<F>(&mut self, two: F) -> Option<Vec<u16>>
    where
        F: Into<Option<Vec<u16>>>,
    {
        let two: Option<Vec<u16>> = two.into();
        std::mem::replace(&mut self.two, two)
    }

    /// Sets the field: `two`. Returns the struct itself.
    #[must_use]
    pub fn with_two<F>(mut self, two: F) -> Self
    where
        F: Into<Option<Vec<u16>>>,
    {
        self.set_two(two);
        self
    }
}

impl UnsignedIntFields {
    //! Field: `three`

    /// Gets the field: `three`.
    #[must_use]
    pub fn three(&self) -> Option<&Vec<u32>> {
        self.three.as_ref()
    }

    /// Sets the field: `three`. Returns the previous value.
    pub fn set_three<F>(&mut self, three: F) -> Option<Vec<u32>>
    where
        F: Into<Option<Vec<u32>>>,
    {
        let three: Option<Vec<u32>> = three.into();
        std::mem::replace(&mut self.three, three)
    }

    /// Sets the field: `three`. Returns the struct itself.
    #[must_use]
    pub fn with_three<F>(mut self, three: F) -> Self
    where
        F: Into<Option<Vec<u32>>>,
    {
        self.set_three(three);
        self
    }
}

impl UnsignedIntFields {
    //! Field: `four`

    /// Gets the field: `four`.
    #[must_use]
    pub fn four(&self) -> Option<&Vec<u64>> {
        self.four.as_ref()
    }

    /// Sets the field: `four`. Returns the previous value.
    pub fn set_four<F>(&mut self, four: F) -> Option<Vec<u64>>
    where
        F: Into<Option<Vec<u64>>>,
    {
        let four: Option<Vec<u64>> = four.into();
        std::mem::replace(&mut self.four, four)
    }

    /// Sets the field: `four`. Returns the struct itself.
    #[must_use]
    pub fn with_four<F>(mut self, four: F) -> Self
    where
        F: Into<Option<Vec<u64>>>,
    {
        self.set_four(four);
        self
    }
}

impl UnsignedIntFields {
    //! Field: `five`

    /// Gets the field: `five`.
    #[must_use]
    pub fn five(&self) -> Option<&Vec<u128>> {
        self.five.as_ref()
    }

    /// Sets the field: `five`. Returns the previous value.
    pub fn set_five<F>(&mut self, five: F) -> Option<Vec<u128>>
    where
        F: Into<Option<Vec<u128>>>,
    {
        let five: Option<Vec<u128>> = five.into();
        std::mem::replace(&mut self.five, five)
    }

    /// Sets the field: `five`. Returns the struct itself.
    #[must_use]
    pub fn with_five<F>(mut self, five: F) -> Self
    where
        F: Into<Option<Vec<u128>>>,
    {
        self.set_five(five);
        self
    }
}
