// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// A variant with floating point slice cases.
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
#[serde(tag = "var", content = "val")]
pub enum FloatCases {
    /// An `f32` slice case.
    One(Vec<proto_packet::types::Float32>),

    /// An `f64` slice case.
    Two(Vec<proto_packet::types::Float64>),
}
