// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A message with time fields.
/// message TimeFields {
///    
///     // A `timestamp` field.
///     one: timestamp = 1;
///    
///     // A `date` field.
///     two: date = 2;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct TimeFields {
    one: Option<i64>,
    two: Option<proto_packet::types::Date>,
}

impl TimeFields {
    //! Field: `one`

    /// Gets the field: `one`.
    #[must_use]
    pub fn one(&self) -> Option<i64> {
        self.one
    }

    /// Sets the field: `one`. Returns the previous value.
    pub fn set_one<F>(&mut self, one: F) -> Option<i64>
    where
        F: Into<Option<i64>>,
    {
        let one: Option<i64> = one.into();
        std::mem::replace(&mut self.one, one)
    }

    /// Sets the field: `one`. Returns the struct itself.
    #[must_use]
    pub fn with_one<F>(mut self, one: F) -> Self
    where
        F: Into<Option<i64>>,
    {
        self.set_one(one);
        self
    }
}

impl TimeFields {
    //! Field: `two`

    /// Gets the field: `two`.
    #[must_use]
    pub fn two(&self) -> Option<proto_packet::types::Date> {
        self.two
    }

    /// Sets the field: `two`. Returns the previous value.
    pub fn set_two<F>(&mut self, two: F) -> Option<proto_packet::types::Date>
    where
        F: Into<Option<proto_packet::types::Date>>,
    {
        let two: Option<proto_packet::types::Date> = two.into();
        std::mem::replace(&mut self.two, two)
    }

    /// Sets the field: `two`. Returns the struct itself.
    #[must_use]
    pub fn with_two<F>(mut self, two: F) -> Self
    where
        F: Into<Option<proto_packet::types::Date>>,
    {
        self.set_two(two);
        self
    }
}
