// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A message with a single boolean slice field.
/// message BooleanField {
///    
///     // A `bool` slice field.
///     one: []bool = 1;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct BooleanField {
    #[serde(skip_serializing_if = "Option::is_none")]
    one: Option<Vec<bool>>,
}

impl BooleanField {
    //! Field: `one`

    /// Gets the field: `one`.
    #[must_use]
    pub fn one(&self) -> Option<&Vec<bool>> {
        self.one.as_ref()
    }

    /// Sets the field: `one`. Returns the previous value.
    pub fn set_one<F>(&mut self, one: F) -> Option<Vec<bool>>
    where
        F: Into<Option<Vec<bool>>>,
    {
        let one: Option<Vec<bool>> = one.into();
        std::mem::replace(&mut self.one, one)
    }

    /// Sets the field: `one`. Returns the struct itself.
    #[must_use]
    pub fn with_one<F>(mut self, one: F) -> Self
    where
        F: Into<Option<Vec<bool>>>,
    {
        self.set_one(one);
        self
    }
}
