// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A message with special slice fields.
/// message SpecialFields {
///    
///     // A `uuid` slice field.
///     one: []uuid = 1;
///    
///     // A `string` slice field.
///     two: []string = 2;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct SpecialFields {
    one: Option<Vec<proto_packet::types::Uuid>>,
    two: Option<Vec<String>>,
}

impl SpecialFields {
    //! Field: `one`

    /// Gets the field: `one`.
    #[must_use]
    pub fn one(&self) -> Option<&Vec<proto_packet::types::Uuid>> {
        self.one.as_ref()
    }

    /// Sets the field: `one`. Returns the previous value.
    pub fn set_one<F>(&mut self, one: F) -> Option<Vec<proto_packet::types::Uuid>>
    where
        F: Into<Option<Vec<proto_packet::types::Uuid>>>,
    {
        let one: Option<Vec<proto_packet::types::Uuid>> = one.into();
        std::mem::replace(&mut self.one, one)
    }

    /// Sets the field: `one`. Returns the struct itself.
    #[must_use]
    pub fn with_one<F>(mut self, one: F) -> Self
    where
        F: Into<Option<Vec<proto_packet::types::Uuid>>>,
    {
        self.set_one(one);
        self
    }
}

impl SpecialFields {
    //! Field: `two`

    /// Gets the field: `two`.
    #[must_use]
    pub fn two(&self) -> Option<&Vec<String>> {
        self.two.as_ref()
    }

    /// Sets the field: `two`. Returns the previous value.
    pub fn set_two<F>(&mut self, two: F) -> Option<Vec<String>>
    where
        F: Into<Option<Vec<String>>>,
    {
        let two: Option<Vec<String>> = two.into();
        std::mem::replace(&mut self.two, two)
    }

    /// Sets the field: `two`. Returns the struct itself.
    #[must_use]
    pub fn with_two<F>(mut self, two: F) -> Self
    where
        F: Into<Option<Vec<String>>>,
    {
        self.set_two(two);
        self
    }
}
