// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// An enum with multiple cases.
#[derive(
    Copy,
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub enum MultiCase {
    /// The first case.
    One,

    /// The second case.
    Two,

    /// The third case.
    Three,
}
