[workspace]
resolver = "3"
members = [
    "proto-packet-cli",
    "proto-packet-compile",
    "proto-packet-gen",
    "proto-packet-link",
    "proto-packet-parse",
    "proto-packet-tree",
    "proto-packet-validate",
]

[workspace.package]
version = "0.0.0"
authors = ["Nik Deapen <nik@deapen.com>"]
repository = "https://github.com/proto-packet/proto-packet"
edition = "2024"
license = "MIT"

[workspace.dependencies]
proto-packet = { path = "../dep/dep-rust" }             # todo -- path dependency
proto-packet-parse = { path = "proto-packet-parse" }    # todo -- path dependency
proto-packet-tree = { path = "proto-packet-tree" }      # todo -- path dependency

clerr = "0.11.0-rc.3"                       # todo -- release candidate
colored = "3.1.1"
custom-string = "0.11.0-rc.2"               # todo -- release candidate
lex = "0.16.0-rc.1"                         # todo -- release candidate
