// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A nested test message.
/// message MoveNested {
///    
///     // The value.
///     value: u32 = 1;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct MoveNested {
    #[serde(skip_serializing_if = "Option::is_none")]
    value: Option<u32>,
}

impl MoveNested {
    //! Field: `value`

    /// Gets the field: `value`.
    #[must_use]
    pub fn value(&self) -> Option<u32> {
        self.value
    }

    /// Sets the field: `value`. Returns the previous value.
    pub fn set_value<F>(&mut self, value: F) -> Option<u32>
    where
        F: Into<Option<u32>>,
    {
        let value: Option<u32> = value.into();
        std::mem::replace(&mut self.value, value)
    }

    /// Sets the field: `value`. Returns the struct itself.
    #[must_use]
    pub fn with_value<F>(mut self, value: F) -> Self
    where
        F: Into<Option<u32>>,
    {
        self.set_value(value);
        self
    }
}
