// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A message in a rust-keyword mod. (`move.pps` must generate `pub mod r#move;`)
/// message MoveTest {
///    
///     // The name.
///     name: string = 1;
///    
///     // The nested value. (exercises the qualified `crate::keywords::r#move::` path)
///     nested: keywords.move.MoveNested = 2;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct MoveTest {
    #[serde(skip_serializing_if = "Option::is_none")]
    name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    nested: Option<crate::keywords::r#move::MoveNested>,
}

impl MoveTest {
    //! Field: `name`

    /// Gets the field: `name`.
    #[must_use]
    pub fn name(&self) -> Option<&str> {
        self.name.as_deref()
    }

    /// Sets the field: `name`. Returns the previous value.
    pub fn set_name<F>(&mut self, name: F) -> Option<String>
    where
        F: Into<Option<String>>,
    {
        let name: Option<String> = name.into();
        std::mem::replace(&mut self.name, name)
    }

    /// Sets the field: `name`. Returns the struct itself.
    #[must_use]
    pub fn with_name<F>(mut self, name: F) -> Self
    where
        F: Into<Option<String>>,
    {
        self.set_name(name);
        self
    }
}

impl MoveTest {
    //! Field: `nested`

    /// Gets the field: `nested`.
    #[must_use]
    pub fn nested(&self) -> Option<&crate::keywords::r#move::MoveNested> {
        self.nested.as_ref()
    }

    /// Sets the field: `nested`. Returns the previous value.
    pub fn set_nested<F>(&mut self, nested: F) -> Option<crate::keywords::r#move::MoveNested>
    where
        F: Into<Option<crate::keywords::r#move::MoveNested>>,
    {
        let nested: Option<crate::keywords::r#move::MoveNested> = nested.into();
        std::mem::replace(&mut self.nested, nested)
    }

    /// Sets the field: `nested`. Returns the struct itself.
    #[must_use]
    pub fn with_nested<F>(mut self, nested: F) -> Self
    where
        F: Into<Option<crate::keywords::r#move::MoveNested>>,
    {
        self.set_nested(nested);
        self
    }
}
