// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// A variant with unsigned integer cases.
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
#[serde(tag = "var", content = "val")]
pub enum UnsignedIntCases {
    /// A `u8` case.
    One(u8),

    /// A `u16` case.
    Two(u16),

    /// A `u32` case.
    Three(u32),

    /// A `u64` case.
    Four(u64),

    /// A `u128` case.
    Five(u128),
}
