// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A message with unsigned integer fields.
/// message UnsignedIntFields {
///    
///     // A `u8` field.
///     one: u8 = 1;
///    
///     // A `u16` field.
///     two: u16 = 2;
///    
///     // A `u32` field.
///     three: u32 = 3;
///    
///     // A `u64` field.
///     four: u64 = 4;
///    
///     // A `u128` field.
///     five: u128 = 5;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct UnsignedIntFields {
    #[serde(skip_serializing_if = "Option::is_none")]
    one: Option<u8>,
    #[serde(skip_serializing_if = "Option::is_none")]
    two: Option<u16>,
    #[serde(skip_serializing_if = "Option::is_none")]
    three: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    four: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    five: Option<u128>,
}

impl UnsignedIntFields {
    //! Field: `one`

    /// Gets the field: `one`.
    #[must_use]
    pub fn one(&self) -> Option<u8> {
        self.one
    }

    /// Sets the field: `one`. Returns the previous value.
    pub fn set_one<F>(&mut self, one: F) -> Option<u8>
    where
        F: Into<Option<u8>>,
    {
        let one: Option<u8> = one.into();
        std::mem::replace(&mut self.one, one)
    }

    /// Sets the field: `one`. Returns the struct itself.
    #[must_use]
    pub fn with_one<F>(mut self, one: F) -> Self
    where
        F: Into<Option<u8>>,
    {
        self.set_one(one);
        self
    }
}

impl UnsignedIntFields {
    //! Field: `two`

    /// Gets the field: `two`.
    #[must_use]
    pub fn two(&self) -> Option<u16> {
        self.two
    }

    /// Sets the field: `two`. Returns the previous value.
    pub fn set_two<F>(&mut self, two: F) -> Option<u16>
    where
        F: Into<Option<u16>>,
    {
        let two: Option<u16> = two.into();
        std::mem::replace(&mut self.two, two)
    }

    /// Sets the field: `two`. Returns the struct itself.
    #[must_use]
    pub fn with_two<F>(mut self, two: F) -> Self
    where
        F: Into<Option<u16>>,
    {
        self.set_two(two);
        self
    }
}

impl UnsignedIntFields {
    //! Field: `three`

    /// Gets the field: `three`.
    #[must_use]
    pub fn three(&self) -> Option<u32> {
        self.three
    }

    /// Sets the field: `three`. Returns the previous value.
    pub fn set_three<F>(&mut self, three: F) -> Option<u32>
    where
        F: Into<Option<u32>>,
    {
        let three: Option<u32> = three.into();
        std::mem::replace(&mut self.three, three)
    }

    /// Sets the field: `three`. Returns the struct itself.
    #[must_use]
    pub fn with_three<F>(mut self, three: F) -> Self
    where
        F: Into<Option<u32>>,
    {
        self.set_three(three);
        self
    }
}

impl UnsignedIntFields {
    //! Field: `four`

    /// Gets the field: `four`.
    #[must_use]
    pub fn four(&self) -> Option<u64> {
        self.four
    }

    /// Sets the field: `four`. Returns the previous value.
    pub fn set_four<F>(&mut self, four: F) -> Option<u64>
    where
        F: Into<Option<u64>>,
    {
        let four: Option<u64> = four.into();
        std::mem::replace(&mut self.four, four)
    }

    /// Sets the field: `four`. Returns the struct itself.
    #[must_use]
    pub fn with_four<F>(mut self, four: F) -> Self
    where
        F: Into<Option<u64>>,
    {
        self.set_four(four);
        self
    }
}

impl UnsignedIntFields {
    //! Field: `five`

    /// Gets the field: `five`.
    #[must_use]
    pub fn five(&self) -> Option<u128> {
        self.five
    }

    /// Sets the field: `five`. Returns the previous value.
    pub fn set_five<F>(&mut self, five: F) -> Option<u128>
    where
        F: Into<Option<u128>>,
    {
        let five: Option<u128> = five.into();
        std::mem::replace(&mut self.five, five)
    }

    /// Sets the field: `five`. Returns the struct itself.
    #[must_use]
    pub fn with_five<F>(mut self, five: F) -> Self
    where
        F: Into<Option<u128>>,
    {
        self.set_five(five);
        self
    }
}
