[package]
name = "proto-packet-validate"
description = "This library aids in validating ProtoPacket schema files."
homepage = "https://github.com/proto-packet/proto-packet/tree/master/compile/proto-packet-validate"
readme = "README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
