// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// A variant with special slice cases.
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
#[serde(tag = "var", content = "val")]
pub enum SpecialCases {
    /// A `uuid` slice case.
    One(Vec<proto_packet::types::Uuid>),

    /// A `string` slice case.
    Two(Vec<String>),
}
