[package]
name = "proto-packet-cli"
description = "This crate provides the ProtoPacket command-line interface."
homepage = "https://github.com/proto-packet/proto-packet/tree/master/compile/proto-packet-cli"
readme = "README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
proto-packet-parse = { workspace = true }
proto-packet-tree = { workspace = true }
proto-packet-validate = { workspace = true }
proto-packet-compile = { workspace = true }

clap = { workspace = true, features = ["derive"] }
clerr = { workspace = true }
file-storage = { workspace = true }
