// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// ```pps
/// // A greeting request.
/// message GreetRequest {
///    
///     // The name to greet.
///     name: string = 1;
/// }
/// ```
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    Default,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
pub struct GreetRequest {
    name: Option<String>,
}

impl GreetRequest {
    //! Field: `name`

    /// Gets the field: `name`.
    #[must_use]
    pub fn name(&self) -> Option<&str> {
        self.name.as_deref()
    }

    /// Sets the field: `name`. Returns the previous value.
    pub fn set_name<F>(&mut self, name: F) -> Option<String>
    where
        F: Into<Option<String>>,
    {
        let name: Option<String> = name.into();
        std::mem::replace(&mut self.name, name)
    }

    /// Sets the field: `name`. Returns the struct itself.
    #[must_use]
    pub fn with_name<F>(mut self, name: F) -> Self
    where
        F: Into<Option<String>>,
    {
        self.set_name(name);
        self
    }
}
