// DO NOT EDIT: This file was generated by the ProtoPacket compiler.
/// A variant with special cases.
#[derive(
    Clone,
    Ord,
    PartialOrd,
    Eq,
    PartialEq,
    Hash,
    Debug,
    proto_packet::serde::Serialize,
    proto_packet::serde::Deserialize,
)]
#[serde(crate = "proto_packet::serde")]
#[serde(tag = "var", content = "val")]
pub enum SpecialCases {
    /// A `uuid` case.
    One(proto_packet::types::Uuid),

    /// A `string` case.
    Two(String),
}
