[package]
name = "proto-packet-link"
description = "This library aids in linking ProtoPacket schema files."
homepage = "https://github.com/proto-packet/proto-packet/tree/master/compile/proto-packet-link"
readme = "README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
proto-packet = { workspace = true }
proto-packet-tree = { workspace = true }

clerr = { workspace = true }
